### ISSUE TITLE
How did you set up log directory name when you conducts different experiments?

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#11]
It seems that the default log directory name is "outputs/". I want to change this name because I need to conduct multiple different experiments. How did you make it?

**Comment by dcharatan** [comment]
The output path is hard-coded on line 9 of `src/misc/LocalLogger.py`:

```
LOG_PATH = Path("outputs/local")
```

This should probably be configurable via Hydra, but unfortunately isn't (although it should be fairly easy to modify). We used the local logger for quick debugging because it's faster to start up than Weights and Biases, which we used to log full training runs. If you use `wandb.mode=offline` or `wandb.mode=online`, you can set `wandb.name` to give each run a unique name and path.

**Comment by thucz** [comment]
Thanks
