### ISSUE TITLE
The meaning of gaussians_per_pixel and num_surfaces

### ISSUE THREAD

**Issue by hxSong22** [dcharatan/pixelsplat#15]
Hi, thanks for your wonderful work! I am confused about the above two parameters. I notice that num_surfaces initialize the number of gaussians per pixel and gaussians_per_pixel control the topK probabilities of depth. Therefore, the final number of gaussians of each pixel equals gaussians_per_pixel*num_surfaces, am I correct? If I am wrong, what's the exact meaning of these two parameters? Besides, if I'd like to modify the gaussians of each pixel, which parameter should I choose to modify?

**Comment by dcharatan** [comment]
The `gaussians_per_pixel` parameter is the number of Gaussians sampled from each per-ray (per-pixel) probability distribution. The `num_surfaces` parameter is the number of independent probability distributions that exist for each ray. As you correctly say, the number of Gaussians per pixel is the product of the two parameters.

Our hypothesis was that by having multiple independent probability distributions for each ray, these distributions could converge around different surfaces. For example, the first and second distributions might always represent the first- and second- closest surfaces from the camera respectively. However, it turns out that having multiple distributions per ray doesn't really do anything, likely because the Real Estate 10k and ACID datasets contain mostly forward-facing scenes, where only one surface per ray is needed. We also found that the network can "cheat" and learn multiple surfaces even with `num_surfaces == 1` by creating checkerboard patterns where pixels alternate between representing near and far surfaces. You can see this effect in figure 3 of the [Splatter Image paper](https://arxiv.org/abs/2312.13150), which describes a similar approach to ours for object-centric scenes.

Which parameter you modify depends on what you're trying to do. Increasing `gaussians_per_pixel` makes training converge slightly faster (the thought is that you get gradients at more depths, so the overall gradient is a bit better). I recommend using `num_surfaces == 1` unless you're trying to train the network on a dataset that looks very different from RE10k/ACID.
