### ISSUE TITLE
how to render the cumulative opacity of target view?

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#18]
I want to use it on the object datasets. I need to constrain the cumulative opacity to zero for the background. Do you how to render the cumulative opacity of the target view? Another question: Is the default background color black[0, 0, 0]? Or white [1, 1, 1]?

**Comment by dcharatan** [comment]
To render the cumulative opacity, I would implement something similar to `render_depth_cuda` in `src/model/decoder/cuda_splatting.py`. You would have to color all rendered Gaussians white and render on a black background instead of coloring the Gaussians according to their depths.

The default background color is black. It's set in `config/dataset/re10k.yaml`. All of the rendering functions in `src/model/decoder/cuda_splatting.py` should support different background colors.

**Comment by thucz** [comment]
Thanks for your reply! I'm very much looking forward to your implementation. This will be of great help to me.
