### ISSUE TITLE
Do we still need the epipolar encoder if the ground-truth camera pose and intrinsic are known?

### ISSUE THREAD

**Issue by Pixie8888** [dcharatan/pixelsplat#20]
Hi,

Do we still need the epipolar encoder if the ground-truth camera pose and intrinsic are known? I guess we don't need it since there is no scale ambiguity anymore?

**Comment by dcharatan** [comment]
pixelSplat is trained using ground-truth camera intrinsics and extrinsics. However, since both are estimated via SfM software like COLMAP, they have ambiguous scale. For example, in one scene (training example), one unit might correspond to one meter, while in another, one unit corresponds to 10 cm. The epipolar encoder helps pixelSplat determine the appropriate scale.

If you have a dataset where all of the scenes have a consistent scale (e.g., 1 unit = 1 meter), then the epipolar encoder becomes unnecessary. However, as far as I know, there’s no suitable dataset that’s widely available where this is the case.
