### ISSUE TITLE
question about extrinsics 

### ISSUE THREAD

**Issue by Warrior456** [dcharatan/pixelsplat#30]
Thank you for your excellent open-source work. I am confused about the extrinsics used in the code, of course I have noticed the Camera Conventions in the readme, but I am still not sure how to convert the extrinsics matrix obtained by colmap into the required format. For example, I now get w2c=[R,T] according to colmap, and I directly invert it to get c2w, but it seems wrong, so I don't know what other operations I need to do to get the camera parameter format that meets the requirements

**Comment by dcharatan** [comment]
Based on COLMAP's [documentation](https://colmap.github.io/format.html) (search for the paragraph that begins with "Here, the first two lines"), here's what you would have to do to convert from COLMAP format:

- Convert the quaternion rotation to a rotation matrix. You can use a library like [SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_quat.html) to do this, but you have to be careful, because there's no uniform convention on whether quaternions are `wxyz` or `xyzw`. If you use SciPy, you have to convert COLMAP's quaternions from `wxyz` to `xyzw`.
- Compute the camera center as described in COLMAP's documentation via $-R^T * T$. This is the camera's position in world space. In our extrinsics format, this becomes the top 3 entries of the rightmost column.
- Invert the rotation provided by COLMAP. This becomes the top left 3x3 entries of our extrinsics format.
- Don't forget to set/add the [0, 0, 0, 1] bottom row.

The reasoning is as follows:

- The coordinate conventions for COLMAP and our code are the same (OpenCV style).
- For the translation, the top 3 entries of the rightmost column represent the world-space camera position. You can convince yourself that this is the case by thinking about what would happen if you multiplied the vector $[0, 0, 0, 1]^T$ (representing a camera at the origin in camera space) with a matrix in our format—the rightmost column of the matrix is "selected," meaning that it must be the world-space camera position.
- For the rotation, COLMAP's format is world-to-camera. To get a camera-to-world rotation, you simply invert the rotation.
