### ISSUE TITLE
How flexible is Min Baseline Requirement

### ISSUE THREAD

**Issue by skrya** [dcharatan/pixelsplat#48]
Hello David, 

Thanks for the work! I see that the minimum baseline requirement is 1e-3 on the datasets. May I know if the method can still produce reasonable result if the  baseline is say > 1e-5 but less than 1e-3, which would happen in an autonomous driving setting? 

Thanks!

**Comment by dcharatan** [comment]
It might still work if you try it out. The main concern is that the code that computes the epipolar lines could become numerically unstable with very small baselines. If I'm remembering correctly, I added `baseline_epsilon` to the RE10k dataset because I figured any baseline smaller than that would correspond to basically no movement anyway (given the scale distribution in RE10k), meaning that smaller baselines wouldn't provide a useful training signal.
