### ISSUE TITLE
How many scenes are there in your selected data for RealEstate10k?

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#5]
Hi! Thanks for your great work. 

I know there are 10k scenes(80k video subsets) in the original dataset. I wonder if you selected all the scenes in your download scripts(500GB)?

**Comment by dcharatan** [comment]
The versions of Real Estate 10k and ACID we used contain the following number of clips:

```
Real Estate 10k
Train: 66033 clips
Test: 7286 clips

ACID
Train: 11069 clips
Test: 1972 clips
```

The number of clips available to us was slightly smaller than the full number of clips because some of the YouTube videos in the original Real Estate 10k and ACID datasets were no longer available when we tried to download them.

It's worth noting that the 500 GB size is for compressed videos at 640x360 resolution.

**Comment by thucz** [comment]
Thanks
