### ISSUE TITLE
How to add depth loss

### ISSUE THREAD

**Issue by SongHaixu** [dcharatan/pixelsplat#66]
Thank you for your excellent work! I want to increase depth loss for my own dataset during the training process. However, I notice that the depth map rendered by Gaussian kernel is colored rather than grayscale. Therefore, when I have the scaled depth value of each pixel's in the image, what should I do to leverage gt depth values to supervise the depth map rendered by Gaussian?

**Comment by dcharatan** [comment]
You should be able to use [this function](https://github.com/dcharatan/pixelsplat/blob/e4d34e8c7827525b3fe71b8bb94f1618f70080e7/src/model/decoder/cuda_splatting.py#L226-L269), which will give you the depth without the color map applied. However, because depth supervision/regularization wasn't a central part of the paper, this approach to rendering depth is kind of hacky (we use the Gaussians' depths as their colors, then render these colors). It might be worth checking out forks of `diff-gaussian-rasterization` that natively support depth rendering, e.g. [this one](https://github.com/JonathonLuiten/diff-gaussian-rasterization-w-depth). Disclaimer: I haven't actually tried the linked repo out myself.
