### ISSUE TITLE
ACID dataset loader

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#7]
It seems that the ACID dataloader is not provided. Could you also provide that file?

**Comment by dcharatan** [comment]
The Real Estate 10k and ACID datasets use exactly the same format, so they use the same data loader. To use ACID instead of Real Estate 10k, simply change the dataset root folder at `config/dataset/re10k.yaml`:

```
roots: [datasets/acid]
```

From the command line, you could instead do the following:

```
python3 -m src.main <other parameters> dataset.roots=[datasets/acid]
```

Note that you should also be able to train using Real Estate 10k and ACID at once, although we never tried this:

```
roots: [datasets/re10k, datasets/acid]
```

**Comment by thucz** [comment]
Thanks
