### ISSUE TITLE
Is there a naming error here?

### ISSUE THREAD

**Issue by chenkangjie1123** [dcharatan/pixelsplat#73]
<img width="506" alt="image" src="https://github.com/dcharatan/pixelsplat/assets/88231160/a738b621-b52e-4fad-a00e-f42ee8f2a6f8">
<img width="542" alt="image" src="https://github.com/dcharatan/pixelsplat/assets/88231160/43e7ae47-ea8e-43a0-bcdc-c4aad5018163">

Hello, I don’t have a deep understanding of the transformer structure, but I still want to ask if there is a naming error before and after. The feature of epipolar sampling was first named Q, but it was actually used as KV?

**Comment by dcharatan** [comment]
The code originally had the q and kv variable names flipped. That got fixed in [this](https://github.com/dcharatan/pixelsplat/commit/7b8f50372b776e9bfc9520f0f63b2fce872ff07a) commit. Make sure you pull the latest code, since it fixes this issue and a few other small issues and has slightly better performance!
