### ISSUE TITLE
support `fp16` training

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#78]
Hi!  I want to train pixelsplat on higher resolution images. But the GPU memory limits my thoughts. Do you know how to adapt your pipeline especially `diff-gaussian-rasterization` module to `fp16` training?

**Comment by dcharatan** [comment]
You should be able to switch the neural network components to FP16 using the steps [here](https://lightning.ai/docs/pytorch/1.5.9/advanced/mixed_precision.html), since the code is based on PyTorch Lightning. `diff-gaussian-rasterization` would be harder to convert to FP16 because you would have to change the CUDA code in a bunch of places and certain operations might not work with FP16 precision. I would start with the neural network parts of pixelSplat, since those are responsible for the vast majority of the memory usage.

**Comment by thucz** [comment]
In fact, I tried to training in precision=16. The `diff-gaussian-rasterization` module will raise errors about the data type.

<img width="1064" alt="image" src="https://github.com/dcharatan/pixelsplat/assets/135981918/6d5c6d23-6c90-4ca0-bbf3-77363f1971db">
