### ISSUE TITLE
Hi! How can I visualize the ply file with RGB colors?

### ISSUE THREAD

**Issue by thucz** [dcharatan/pixelsplat#81]
I cannot find out the entry to import the .ply file for Polycam. How did you make it?

**Comment by dcharatan** [comment]
I posted a response about this [here](https://github.com/dcharatan/pixelsplat/issues/43#issuecomment-1968346000) earlier. I think Polycam may have since removed the ability to upload and visualize `.ply` files, although I'm not sure. Since `.ply` is the "standard" Gaussian splatting file type, it should be possible to use other Gaussian viewers instead.
