### ISSUE TITLE
Issue about gaussians_per_pixel

### ISSUE THREAD

**Issue by Doctor-James** [dcharatan/pixelsplat#85]
Thank you for your outstanding work. I would like to ask when the value of gaussians_per_pixel is not 1, do the Gaussian points corresponding to each pixel share parameters such as scale, rotations, etc.?

**Comment by dcharatan** [comment]
The relevant code is here:

https://github.com/dcharatan/pixelsplat/blob/dea327d24820b59c5293677fc1f5e6557617430d/src/model/encoder/encoder_epipolar.py#L165-L173

The scales, rotations, and colors (spherical harmonics) come from the `raw_gaussians` parameter to this function. They're shared for each pixel when `gaussians_per_pixel` is greater than 1. Note that there's also a `num_surfaces` configuration, which will give different scales, rotations, and colors for different samples for the same pixel (`num_surfaces` different groups of `gaussians_per_pixel` samples with the same Gaussian parameters). We didn't end up using `num_surfaces > 1` because it didn't seem to make a difference.
