### ISSUE TITLE
computing metrics

### ISSUE THREAD

**Issue by Warrior456** [dcharatan/pixelsplat#92]
Thank you for your outstanding work.
I run 
```python3 -m src.main +experiment=re10k mode=test dataset/view_sampler=evaluation dataset.view_sampler.index_path=assets/evaluation_index_re10k.json checkpointing.load=checkpoints/re10k.ckpt```
and then 
```python3 -m src.scripts.compute_metrics +experiment=re10k +evaluation=re10k```
However, the compute_metrics script ends early(ends at 6473/7286), below:
![image](https://github.com/user-attachments/assets/f5e92a36-1a16-4a8a-acfd-37f047909dff)
And the metrics are not print or saved.

I have no idea about it. Look forward to your reply.

**Comment by dcharatan** [comment]
This is expected. Some of the scenes get filtered out. You'll have to double-check, but I think it's probably happening [here](https://github.com/dcharatan/pixelsplat/blob/dea327d24820b59c5293677fc1f5e6557617430d/src/dataset/view_sampler/view_sampler_evaluation.py#L58), since some scenes are too short (not enough frames) to be included in the evaluation index.
