### ISSUE TITLE
How to understand extrintic in *torch or dataset_re10k.py

### ISSUE THREAD

**Issue by YooWang** [dcharatan/pixelsplat#98]
Hi, thank you very much for your excellent work. I am still confused about extrinsics and hope to get your help. I understand that the extrinsics used are OpenCV-style camera-to-world matrices（[camera convertions](https://github.com/dcharatan/pixelsplat?tab=readme-ov-file#camera-conventions)）. In the code src/dataset/dataset_re10k.py, in [convert_poses,](https://github.com/dcharatan/pixelsplat/blob/main/src/dataset/dataset_re10k.py#L179) the pose is read, and the result is w2c, and then converted to c2w? Are the extrinsics in *.torch obtained by processing the dataset through RealEstate10kTools w2c? I am confused about whether the format of the *.torch file is w2c or c2w, and the c2w used in the Camera [Conventions](https://github.com/dcharatan/pixelsplat?tab=readme-ov-file#camera-conventions) refers to the requirement for the pose of the dataset(*.torch) or the requirement for [w2c.inverse()?](https://github.com/dcharatan/pixelsplat/blob/main/src/dataset/dataset_re10k.py#L200)

Thank you very much and looking forward to your reply.

**Comment by dcharatan** [comment]
The `.torch` dataset just stores exactly what the original Real Estate 10k dataset stored, which is an 18-dimensional vector that contains both intrinsics and w2c poses for each camera. The camera conventions refer to what the pixelSplat model itself uses after conversion. So, to answer your questions:

> In the code src/dataset/dataset_re10k.py, in [convert_poses,](https://github.com/dcharatan/pixelsplat/blob/main/src/dataset/dataset_re10k.py#L179) the pose is read, and the result is w2c, and then converted to c2w?

Yes, exactly.

> Are the extrinsics in *.torch obtained by processing the dataset through RealEstate10kTools w2c?

Yes, they're w2c, since the camera metadata is unchanged compared to the original Real Estate 10k format.

> I am confused about whether the format of the .torch file is w2c or c2w, and the c2w used in the Camera [Conventions](https://github.com/dcharatan/pixelsplat?tab=readme-ov-file#camera-conventions) refers to the requirement for the pose of the dataset(.torch) or the requirement for [w2c.inverse()?](https://github.com/dcharatan/pixelsplat/blob/main/src/dataset/dataset_re10k.py#L200)

The `.torch` files contain w2c poses. The data loaders are expected to return values that follow the [camera conventions](https://github.com/dcharatan/pixelsplat?tab=readme-ov-file#camera-conventions), which is why the RE10k loader converts from w2c to c2w.

Hope this helps!

**Comment by YooWang** [comment]
Thanks very much for answering！
